CASES_DIR: "./cases"
CASES_PREFIX: "/home/marsdenlab/datasets/vascular_data"

LEAK: 0.2
BATCH_SIZE: 4
LEARNING_RATE: 0.0001
TRAIN_STEPS: 35000
PRINT_STEP: 200
INIT: 0.07
L2_REG: 0.0001
NUM_FILTERS: 32
QUEUE_SIZE: 500
NUM_THREADS: 200
THRESHOLD: 0.2
PR_INTERVALS: 30
