CASES_DIR: "./cases"
CASES_PREFIX: "/home/marsdenlab/datasets/vascular_data"

LEAK: 0.2
CROP_DIMS: 128
IMAGE_DIMS: 192
BATCH_SIZE: 4
LEARNING_RATE: 0.0001
TRAIN_STEPS: 40000
PRINT_STEP: 200
INIT: 0.04
L2_REG: 0.0001
NUM_FILTERS: 32
QUEUE_SIZE: 500
NUM_THREADS: 16
THRESHOLD: 0.3
PR_INTERVALS: 30
